import { Advent_Pro } from 'next/font/google'
import './globals.css'

const adventPro = Advent_Pro({
  weight: '400',
  preload: false,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={adventPro.className}>{children}</body>
    </html>
  )
}
